// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAttctw_C4zk3Hju7vHatc2ItWnabJFm_Q',
    appId: '1:204008202821:web:d993f118d234e03fdff92c',
    messagingSenderId: '204008202821',
    projectId: 'storeapp-56f38',
    authDomain: 'storeapp-56f38.firebaseapp.com',
    databaseURL: 'https://storeapp-56f38-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-56f38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxPweQBfM6QZkzMcxqb-uPEP3FIJLwEy8',
    appId: '1:204008202821:android:aa95852d18f2269ddff92c',
    messagingSenderId: '204008202821',
    projectId: 'storeapp-56f38',
    databaseURL: 'https://storeapp-56f38-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-56f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRWMxi3gFMQsOPnbDk2cHEYlLC-KjT5wk',
    appId: '1:204008202821:ios:2ebc58e8a0a8aeeddff92c',
    messagingSenderId: '204008202821',
    projectId: 'storeapp-56f38',
    databaseURL: 'https://storeapp-56f38-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-56f38.firebasestorage.app',
    iosBundleId: 'co.edu.unab.damo.ltortiz.storeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRWMxi3gFMQsOPnbDk2cHEYlLC-KjT5wk',
    appId: '1:204008202821:ios:2ebc58e8a0a8aeeddff92c',
    messagingSenderId: '204008202821',
    projectId: 'storeapp-56f38',
    databaseURL: 'https://storeapp-56f38-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-56f38.firebasestorage.app',
    iosBundleId: 'co.edu.unab.damo.ltortiz.storeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAttctw_C4zk3Hju7vHatc2ItWnabJFm_Q',
    appId: '1:204008202821:web:afa0d01e93ce36addff92c',
    messagingSenderId: '204008202821',
    projectId: 'storeapp-56f38',
    authDomain: 'storeapp-56f38.firebaseapp.com',
    databaseURL: 'https://storeapp-56f38-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-56f38.firebasestorage.app',
  );
}